# Generated by Django 6.0.4 on 2026-04-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('auth_method', models.CharField(choices=[('gkeepapi', 'gkeepapi'), ('oauth', 'oauth')], max_length=16)),
                ('lines_imported', models.PositiveIntegerField()),
                ('lines_skipped', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
